### ISSUE TITLE
Unable to Use Custom Swipe as Portal Template

### ISSUE THREAD

**Issue by marissaAnn** [Esri/storymap-swipe#25]
After using the developer steps to customize the Swipe application - I then tried to follow the below instructions to add it to our configurable applications portal gallery (an on premise portal):
https://developerscorner.storymaps.arcgis.com/getting-the-most-out-of-your-customized-storytelling-app-part-2-5b7aa2dc49b3 

I first noticed when I added the custom app to portal, it has "credits used" under usage (and errors when trying to create a report). When trying to create an app, I am continually prompted for an ArcGIS Online account sign in. After signing in - I see "Fatal error: The story cannot be loaded" with a developer tools error of "Error: Item does not exist or is inaccessible."

I then attempted to add it as a custom app on our ArcGIS Online portal - which did load the builder, but still prompted  for an ArcGIS Online log in. 

Looking for some direction on what might need to be configured in the application in order for it to be used as a portal template with our on-premise portal? From the various documentation, it was unclear how to accomplish this.

**Comment by ssylvia** [comment]
Did you edit the swipe-config file with the correct config for your portal?
https://github.com/Esri/storymap-swipe#is-the-template-available-in-portal-for-arcgis
https://github.com/Esri/storymap-swipe/blob/master/Swipe/src/app/swipe-config.js#L52 (Line 52 - end), especially default sharing url and proxy url.

**Comment by marissaAnn** [comment]
Yup that did it! My apologizes, I must have overlooked those steps. Thanks for the help!
