### ISSUE TITLE
Add OAuth to the swipe template

### ISSUE THREAD

**Issue by mmurph07** [Esri/storymap-swipe#28]
I work in an organization where story maps are often developed in an intranet environment. It seems most other story map templates have OAuth 2.0 authentication so that we can just register an app and then place the registration key in the index.html file, which allows our intranet environment to communicate with AGOL. From what I have been told by Esri tech support, authentication is not included in the swipe/spyglass template. Can you add that?

Thanks,
Mark

**Comment by cooney** [comment]
Hey Mark,

Yes, I just updated the repo to include support for using OAuth.

**Comment by mmurph07** [comment]
Wow Mark, that was fast! You're awesome - thanks for the quick turnaround!
